### ISSUE TITLE
why does this app continously request access to my google account?

### ISSUE THREAD

**Issue by JackDotJS** [spacecowboy/NotePad#460] opened 2022-12-25 18:45 UTC
<p float="left">
  <img src="https://user-images.githubusercontent.com/31686191/209478802-da969f99-61af-45c9-9f84-7e8d64a391ea.png" width="40%" />
  <img src="https://user-images.githubusercontent.com/31686191/209478808-d48b7840-5bb4-4e7c-adb0-fb88e1b683eb.png" width="40%" /> 
</p>

im loving this app so far. it works perfectly for my needs, especially with the widget functionality. but for some damn reason, every time i open it and do anything, i get the notification in the above image. it's a system notification, so it can't be dismissed or turned off.

i tap "deny" but it still comes back every time. the cycle repeats.

why does this app even need access to begin with? why does it keep asking despite me denying it?

**Comment by Rawng** [comment] 2022-12-26 19:21
I also have this issue. Android version 12 on a Samsung phone. No mods or roots etc installed. The notification _does_ go away when I dismiss it, but returns periodically. I installed 7.0.0 from fdroid and updated to 7.1.0 just a bit ago. The update does not appear to have fixed the issue, though the changelog in the app doesn't show 7.1.0 so I don't know if I'm still running some kind of cached version.

Some light testing leads me to think the request is triggered upon saving a note when exiting the note entry screen.

**Comment by JackDotJS** [comment] 2022-12-26 21:30
@CampelloManuel thanks for getting back so quickly! hope you had a great holiday/weekend 😄 

- up until now, i was using 7.0.0 from f-droid. 7.1.0 does not fix the issue.
- i'm on a google pixel 7 pro running GrapheneOS. it's android 13.
- the notification has come up well over 10 times now.
- this was fresh install since I just got this phone for christmas. 7.0.0 was the oldest version i had

i can also confirm @Rawng's theory. the notification seems to get triggered mainly when saving or deleting notes.

**Comment by JackDotJS** [comment] 2022-12-26 22:16
> Also, since you like the widget, do you have any requests or suggestions on how to improve it ?

i almost missed this part! sorry!

i do have one major suggestion, which is an option to show *completed* tasks. being able to know at a glance what is *and* isn't done would be very nice imo.

more color options would also be nice. the only options right now are between "light" and "dark", and they don't even affect the widget header.

i could put these suggestions in their own issues if that'd be better for you guys.

**Comment by connect2400** [comment] 2022-12-28 16:18
> Hi, thank you for reaching out. A few questions, if you don't mind:
> 
> * what app version ? 7.0.0 from f-droid ?
> * what device ? google, xiaomi, samsung, motorola ?
> * what android version ? I assume android 13 ?
> * did you install any mod, root, xposed software ?
> * the notification really does not go away if you dismiss it ~ 5 times ?
> * did you have version 5.7.1 previously ? or did you install only 7.0.0 ?
> 
> Possibile causes: There is some code for google tasks synchronization that I did not delete yet. I guess it's asking for the google account. I have no idea why, I removed all account permissions and It doesn't happen in my emulator. Don't worry about privacy, I removed all network permissions and the network code doesn't run, so the app is 100% offline. Yeah it _asks_ for the google account, but the code that uses it does not work. Also I can't replicate this. It may be due to the manufacturer doing something weird ?

Hi Manuel,
I just installed the app a couple days ago and I'm liking it so far too. But I have the same kind of complaint as here, with slightly different circumstances, so I thought I'd put my two cents in to help the developer make the most appropriate changes.
I have multiple Google accounts registered on my unrooted Moto G Pure running Android 11 and version 7.0.0 of NoNonsense Notes from F-Droid. I approved permission to access one Google account, assuming it's for backup purposes, but I denied others; there's no legitimate reason the app could need access to ALL Google accounts.
Dismissing the notification (which arises only for the unapproved accounts) only shuts it up for a few minutes. It asks again indefinitely.
This is actually not only annoying but concerning. I recommend that you not only kill whatever process is spawning these notifications -- if the user wants to change access he can bring up the prompt himself in the app native settings -- but add some explanation within the same location as to why access is needed and how access is used (including frequency), if not options for managing the app's usage of Google Drive, etc.
Even if the app needs to sync files for legitimate reasons, it doesn't need to do it every five minutes. I don't make changes to my to-do list that often.
Thank you for your attention to this project. Please let me know if you have any questions or if there's anything I can do.
connect2400

**Comment by connect2400** [comment] 2022-12-28 16:20
P.S. I see you mentioned Google Drive isn't actually being used anymore. I didn't realize this; I *want* cloud backup. So that feature is not present, and not coming back?

**Comment by connect2400** [comment] 2023-01-03 17:06
Because I had actually granted permissions to shut it up, I reset the app (first exporting a backup, which subsequently reloaded fine) by uninstalling and reinstalling version 7.1.0. The notifications came right back up, so I then updated via F-Droid app to 7.1.1. So far so good.

Incidentally, the About screen doesn't state the version number...

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by JackDotJS** [comment] 2023-01-03 17:14
updated! but it seems the update hasn't changed anything in my case :/

ive even restarted my phone just for good measure, but no luck. denying the permission also still does nothing, if anyone happens to wonder.

**Comment by JackDotJS** [comment] 2023-01-03 17:19
also just tried a complete re-install, still nothing.

**Comment by spacecowboy** [comment] 2023-01-03 20:53
@CampelloManuel you should delete `GoogleTasksClient.java` this is where the account permission is originating from. Specifically the `OAUTH_SCOPE`. I admit I can't find the reference to it but deleting it should reveal that

**Comment by connect2400** [comment] 2023-01-04 13:48
Yeah, fyi, 7.1.1 does still request permission ONCE after each reboot for me

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by CampelloManuel** [comment] 2023-01-08 15:18
New update is out. Please tell me if the google account popup is still there.

**Comment by JackDotJS** [comment] 2023-01-08 15:49
nope, still there for me. fresh install once again for good measure but no change. :(

**Comment by CampelloManuel** [comment] 2023-01-08 16:08
I see.
Does the logcat say anything ?
(here is a guide on how to [make a logcat](https://f-droid.org/docs/Getting_logcat_messages_after_crash/) )

**Comment by JackDotJS** [comment] 2023-01-08 17:00
i'll try setting up that logging later today

**Comment by JackDotJS** [comment] 2023-01-09 05:07
well i managed to get *something*... maybe probably.
the log was getting spammed like crazy from all sorts of crap so good luck sifting through this lol

[logcat.txt](https://github.com/spacecowboy/NotePad/files/10370468/logcat.txt)

**Comment by urmomsangus** [comment] 2023-01-11 21:52
Seems to be fixed in 7.1.3 from F-Droid

**Comment by JackDotJS** [comment] 2023-01-11 21:55
can confirm! new update has finally fixed it 😄
thank you so much @CampelloManuel!

**Comment by CampelloManuel** [comment] 2023-01-12 07:18
Good. Others confirmed by email that it works for them, too.
The problem was `AbstractThreadedSyncAdapter` being started in a background service: that was requesting access to every google account, it looks like.
I'll be careful if we ever add something that requires a google account, 
but since that's not planned, I think this problem is solved.

**Closed by CampelloManuel** 2023-01-12 07:18 UTC
Labels: bug
