### ISSUE TITLE
Program seems to remove tasklists from Google Tasks [major data loss]

### ISSUE THREAD

**Issue by MarSoft** [spacecowboy/NotePad#286] opened 2015-01-23 12:34 UTC
I was using this app couple of months ago, primarily as a GTasks client. Later I decided to switch to another client, also with GTasks support. Still NoNoncenceNotes left on my phone, configured but unused.
Now it's the third time most of my tasklists on GoogleTasks vanished. Looking at the code, I see that this app deletes tasklist from Google if it thinks it was deleted locally. But while you generally can restore deleted task, deleted tasklist is not recoverable. So this behaviour caused a notable data loss.
I would suggest adding an option to disallow tasklist removal from Google, for those who use GoogleTasks as a main storage and don't want to lose their data.

**Comment by spacecowboy** [comment] 2015-01-23 23:03
Thanks for reporting and adding information to this bug (duplicate of #276 #260).
It's a bug I have had no success in replicating, despite multiple reports.

Your idea for a temporary workaround might be worth implementing, though reports indicate that single tasks can be deleted as well. Although, disallowing all deletes could be an idea too...

Remember that all notes are recoverable from the 'Archive' (pain in the ass if it deletes the entire list, but it's something).

To be able to actually solve the issue however: can you remember any common usage patterns when the data loss occurred? Something like "editing locally, then editing on Google Tasks, then later the app deleted it all"?

**Comment by MarSoft** [comment] 2015-01-27 19:29
Actually I doubt this is a duplicate. My problem is that I didn't use your
so for long time, and used pain Google Tasks web interface in conjunction
with another a Android client. And in GTasks there is no "archive" folder,
as I could realise. So in GTasks any tasklist deletion leads to permanent
removal of all its tasks.
24 янв. 2015 г. 2:03 пользователь "Space Cowboy" <notifications@github.com>
написал:

**Closed** 2022-10-24 10:07 UTC
